baseURL= "localhost:1313"
languageCode= "en"
title= "Hugo Boilerplate"
paginate = 5
copyright = "All rights reserved - 2018"
theme = "rustytheme"
disableKinds = ["taxonomy", "taxonomyTerm"]
uglyURLS = true
relativeURLS = true
cloudinary_url = "https://res.cloudinary.com/rustycloud/image/upload/"

[params]
  description = "Welcome to my website"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "/img/darius-soodmand-116253.jpg"
  author = "YOUR_NAME"
  authorlocation = "Earth, Milky Way Galaxy"
  authorwebsite = ""
  authorbio= ""
  logo = ""
  hjsStyle = "default"
  paginatedsections = ["posts"]