name = "rustytheme-for-hugo"
licenselink = "https://github.com/rbaylis91"
description = "Rusty theme, used for blog"
homepage = "https://www.russellbaylis"
tags = ["blog"]

[author]
  name = "Russell Baylis"
  homepage = "http://russellbaylis.com"

[original]
  name = "Rustytheme"
  homepage = "https://www.russellbaylis"
  repo = "https://www.russellbaylis"
