---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: hugo/content/post
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: https://res.cloudinary.com/rustycloud/image/upload
front_matter_path: https://res.cloudinary.com/rustycloud/image/upload
use_front_matter_path: true
file_template: ":filename:"
version: '0.48'
