---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: hugo/content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.48'
